public enum Theme {
    SPLASH_WEEK,
    LOST_IN_SPACE,
    UNDER_THE_SEA,
    ENCHANTED_FOREST,
    PIRATES,
    SAFARI_SEASON,
    SUPERHEROES,
    DINOSAUR_WEEK,
    TREASURE_HUNT,
    SHARK_WEEK
}